#!/bin/bash
total 16
-rwxr--r-- 1 root root   66 Aug 31 19:05 0-current_working_directory
-rw-r--r-- 1 root root   47 Aug 31 19:15 1-listit
-rwxr--r-- 1 root root    3 Aug 31 19:33 2-bring_me_home
-rw-r--r-- 1 root root    0 Aug 31 19:35 3-listfiles
-rw-r--r-- 1 root root 1273 Aug 31 18:59 README.md

