#!/bin/bash
total 20
drwxr-xr-x 2 root root  139 Aug 31 19:38 .
drwxr-xr-x 4 root root   60 Aug 31 18:52 ..
-rwxr--r-- 1 root root   66 Aug 31 19:05 0-current_working_directory
-rw-r--r-- 1 root root   47 Aug 31 19:15 1-listit
-rwxr--r-- 1 root root    3 Aug 31 19:33 2-bring_me_home
-rw-r--r-- 1 root root  289 Aug 31 19:35 3-listfiles
-rw-r--r-- 1 root root    0 Aug 31 19:38 4-listmorefiles
-rw-r--r-- 1 root root 1273 Aug 31 18:59 README.md

