#!/bin/bash
total 24
drwxr-xr-x 2 0 0  167 Aug 31 19:44 .
drwxr-xr-x 4 0 0   60 Aug 31 18:52 ..
-rwxr--r-- 1 0 0   66 Aug 31 19:05 0-current_working_directory
-rw-r--r-- 1 0 0   47 Aug 31 19:15 1-listit
-rwxr--r-- 1 0 0    3 Aug 31 19:33 2-bring_me_home
-rw-r--r-- 1 0 0  289 Aug 31 19:35 3-listfiles
-rw-r--r-- 1 0 0  433 Aug 31 19:38 4-listmorefiles
-rw-r--r-- 1 0 0    0 Aug 31 19:44 5-listfilesdigitonly
-rw-r--r-- 1 0 0 1273 Aug 31 18:59 README.md

